version: "3.8"

x-app-volumes: &app-volumes
  - ./src:/usr/app/src
  - ./tests:/usr/app/tests
  - app-vendor:/usr/app/vendor

volumes:
  app-vendor:

networks:
  app:

services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
    networks:
      - app
    <<: *app-volumes
